name: mediastack-homepage

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped

    environment:
      HOMEPAGE_ALLOWED_HOSTS: "192.168.1.69,localhost,media"

    volumes:
      - /opt/media/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro

    healthcheck:
      test:
        - CMD-SHELL
        - wget -q -O /dev/null http://127.0.0.1:3000/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

    networks:
      - mediastack_proxy

networks:
  mediastack_proxy:
    external: true
